import { atom } from "jotai";

export const randomShows = atom(["Harry Potter",
    "Star Wars",
    "The Lord of the Rings: The Fellowship of the Ring",
    "Deadpool",
    "The Fast and the Furious",
    "Dr. No",
    "Jurassic Park",
    "Mission: Impossible",
    "Pirates of the Caribbean",
    "Transformers",
    "X-Men",
    "The Hunger Games",
    "The Chronicles of Narnia",
    "Toy Story",
    "The Matrix",
    "Die Hard",
    "Mad Max: Fury Road",
    "Hobbit",
    "The Terminator",
    "The Godfather",
    "Game of Thrones",
    "Stranger Things",
    "Breaking Bad",
    "The Crown",
    "Friends",
    "The Mandalorian",
    "The Simpsons",
    "The Office",
    "Black Mirror",
    "Westworld",
    "Star Trek",
    "The Witcher",
    "Chernobyl",
    "Fleabag",
    "The Handmaid's Tale",
    "Mindhunter",
    "The Umbrella Academy",
    "The Boys",
    "Money Heist",
    "Narcos",
    "Peaky Blinders",
    "Thor",
  ])

export const movies = atom([
  "Avengers: Endgame",
  "Avengers: Infinity War",
  "Avengers",
  "The Lord of the Rings: The Two Towers",
  "The Hobbit: The Battle of the Five Armies",
  "Deadpool & Wolverine",

  "Harry Potter",
"Star Wars",
"The Lord of the Rings: The Fellowship of the Ring",
"Deadpool",
"The Fast and the Furious",
"Dr. No",
"Jurassic Park",
"Mission: Impossible",
"Pirates of the Caribbean",
"Transformers",
"X-Men",
"The Hunger Games",
"The Chronicles of Narnia",
"Toy Story",
"The Matrix",
"Die Hard",
"Mad Max: Fury Road",
"Hobbit",
"The Terminator",
"The Godfather",
"Iron Man",
"Terminator 2",
"Hulk",
"Star Trek",
"John Wick",
"Avengers",
"Avatar",
"The Wolverine",
"Indiana Jones",
"Back to the Future",
"Ghostbusters",
"Planet of the Apes",
"Alien",
"Predator",
"Captain America",
"The Bourne",
"Spider-Man",
"Men in Black",
"Jurassic Park",
"Thor"]);

export const series = atom([
    "Game of Thrones",
    "Stranger Things",
    "Breaking Bad",
    "The Crown",
    "Friends",
    "The Mandalorian",
    "The Office",
    "Star Trek: Discovery",
    "The Witcher",
    "The Big Bang Theory",
    "How I Met Your Mother",
  ]);

export const animeList = atom([
    "Naruto: Shippuden",
    "Demon Slayer: Kimetsu no Yaiba",
    "One Punch Man",
    "Death Note",
    "Attack on Titan",
    "One Piece",
    "Pokemon",
  ]);

export const latest = atom([
  "Transformers: Rise of the Beasts",
  "Ant-Man and the Wasp: Quantumania",
  "The Flash",
  "Spider-Man: Across the Spider-Verse",
  "No Hard Feelings",
  "John Wick: Chapter 4"
]);