import { atom } from "jotai";

export const randomShows = atom(["Harry Potter",
    "Star Wars",
    "The Lord of the Rings: The Fellowship of the Ring",
    "Deadpool",
    "The Fast and the Furious",
    "Dr. No",
    "Jurassic Park",
    "Mission: Impossible",
    "Pirates of the Caribbean",
    "Transformers",
    "X-Men",
    "The Hunger Games",
    "The Chronicles of Narnia",
    "Toy Story",
    "The Matrix",
    "Die Hard",
    "Mad Max: Fury Road",
    "Hobbit",
    "The Terminator",
    "The Godfather",
    "Game of Thrones",
    "Stranger Things",
    "Breaking Bad",
    "The Crown",
    "Friends",
    "The Mandalorian",
    "The Simpsons",
    "The Office",
    "Black Mirror",
    "Westworld",
    "Star Trek",
    "The Witcher",
    "Chernobyl",
    "Fleabag",
    "The Handmaid's Tale",
    "Mindhunter",
    "The Umbrella Academy",
    "The Boys",
    "Money Heist",
    "Narcos",
    "Peaky Blinders",
    "Thor",
  ])

export const movies = atom(["Harry Potter",
"Star Wars",
"The Lord of the Rings: The Fellowship of the Ring",
"Deadpool",
"The Fast and the Furious",
"Dr. No",
"Jurassic Park",
"Mission: Impossible",
"Pirates of the Caribbean",
"Transformers",
"X-Men",
"The Hunger Games",
"The Chronicles of Narnia",
"Toy Story",
"The Matrix",
"Die Hard",
"Mad Max: Fury Road",
"Hobbit",
"The Terminator",
"The Godfather",
"Iron Man",
"Terminator 2",
"Hulk",
"Star Trek",
"John Wick",
"Avengers",
"Avatar",
"The Wolverine",
"Indiana Jones",
"Back to the Future",
"Ghostbusters",
"Planet of the Apes",
"Alien",
"Predator",
"Captain America",
"The Bourne",
"Spider-Man",
"Men in Black",
"Jurassic Park",
"Thor"]);

export const series = atom(["Game of Thrones",
    "Stranger Things",
    "Breaking Bad",
    "The Crown",
    "Friends",
    "The Mandalorian",
    // "The Simpsons",
    // "The Office",
    // "Black Mirror",
    "Westworld",
    "Star Trek: Discovery",
    "The Witcher",
  ]);

export const animeList = atom(["Attack on Titan",
    "One Piece",
    "My Hero Academia",
    "Fullmetal Alchemist: Brotherhood",
    "Sword Art Online",
    "Naruto",
    "Fairy Tail",
    "Magi: The Labyrinth of Magic",
    "Black Clover",
    "Overlord",
    "Cowboy Bebop",
    "Steins;Gate",
    "Neon Genesis Evangelion",
    "Ghost in the Shell",
    "Psycho-Pass",
    "Clannad",
    "Your Lie in April",
    "Toradora!",
    "Fruits Basket",
    "Anohana: The Flower We Saw That Day",
    "One Punch Man",
    "Gintama",
    "Nichijou",
    "Konosuba: God's Blessing on This Wonderful World!",
    "The Devil is a Part-Timer!",
    "Death Note",
    "Monster",
    "The Promised Neverland",
    "Higurashi When They Cry",
    "Paranoia Agent",
    "March Comes in Like a Lion",
    "Barakamon",
    "Non Non Biyori",
    "A Silent Voice",
    "Demon Slayer: Kimetsu no Yaiba",
    "Blue Exorcist",
    "Noragami",
    "Seraph of the End",
    "Tokyo Ghoul",
    "Haikyuu!!",
    "Kuroko no Basket",
    // "Yuri on Ice",
    "Free!",
    "Ace of Diamond",
    "Re:Zero - Starting Life in Another World",
    "No Game No Life",
    "That Time I Got Reincarnated as a Slime",
    "Log Horizon",
    "The Rising of the Shield Hero"
  ]);

export const latest =  atom(["Transformers: Rise of the Beasts","Ant-Man and the Wasp: Quantumania","The Flash","Spider-Man: Across the Spider-Verse","No Hard Feelings","John Wick: Chapter 4",]);