import { atom } from "jotai";

export const searchResults = atom([]);

export const randomResults = atom([]);

export const movies = atom(["Harry Potter",
"Star Wars",
"The Lord of the Rings: The Fellowship of the Ring",
"Deadpool",
"The Fast and the Furious",
"Dr. No",
"Jurassic Park",
"Mission: Impossible",
"Pirates of the Caribbean",
"Transformers",
"X-Men",
"The Hunger Games",
"The Chronicles of Narnia",
"Toy Story",
"The Matrix",
"Die Hard",
"Mad Max: Fury Road",
"Hobbit",
"The Terminator",
"The Godfather",
"Iron Man",
"Terminator 2",
"Hulk",
"Star Trek",
"John Wick",
"Avengers",
"Avatar",
"The Wolverine",
"Indiana Jones",
"Back to the Future",
"Ghostbusters",
"Planet of the Apes",
"Alien",
"Predator",
"Captain America",
"The Bourne",
"Spider-Man",
"Men in Black",
"Jurassic Park",
"Thor"]);